### ISSUE TITLE
The .exe file is loaded and nothing happens

### ISSUE THREAD

**Issue by Bluesky321321** [Barnacle/USF4-Character-Extractor#5] opened 2021-05-15 15:40 UTC
Sorry, the EXE file can’t be opened. The file is loaded and nothing happens.I don’t know how to use it.

**Comment by Barnacle** [comment] 2021-05-16 12:13
No errors or anything? Maybe there is some kind of log in `eventvwr`

If you can't compile and debug the code yourself, you can try to run this debug build. Maybe some error will finally pop up.
[Debug.zip](https://github.com/Barnacle/USF4-Character-Extractor/files/6489180/Debug.zip)

**Comment by MartinMatsumoto** [comment] 2021-09-04 14:14
I also had the same problem. There was no response when I clicked on the exe file, and even I failed to run the source code. The line 69 of the wrapper.h file reported an error "System.NullReferenceException" and m_pRenderer was null.

**Comment by Barnacle** [comment] 2021-09-04 19:38
Thanks for the info. Not sure what's causing this problem yet, IIRC m_pRenderer should never be null, hmm...

**Comment by Q4st** [comment] 2021-09-09 14:54
Please fix no response when running on win10 64-bit ！

**Comment by Q4st** [comment] 2021-09-09 15:00
System.NullReferenceException
  HResult=0x80004003
  Message=未将对象引用设置到对象的实例。
  Source=USF4ce
  StackTrace:
   在 usf4_ce.MainForm.MainForm_SizeChanged(Object sender, EventArgs e) 在 C:\Users\LiangZ\Desktop\USF4-Character-Extractor-master\USF4-Character-Extractor-master\main\main.h 中: 第 1619 行

**Comment by Barnacle** [comment] 2021-09-10 00:13
@qq1035732175 Hi, thanks for the report. Don't know what's the problem there, but I would suggest to install legacy DX runtime. So maybe this will solve this issue.
https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=35

**Comment by Q4st** [comment] 2021-09-12 16:24
I installed the DX runtime library, the situation is still the same, the running software does not respond!

**Comment by Q4st** [comment] 2021-09-12 16:30
It should be a problem with D3D.DLL,If you are using Win10, please use Win10 to compile once to test the effect.

**Comment by Barnacle** [comment] 2021-09-12 21:46
I'm using Win7, sorry. People tested it on Win10, it should work with no problem.

**Comment by MartinMatsumoto** [comment] 2021-09-13 01:37
> I'm using Win7, sorry. People tested it on Win10, it should work with no problem.

I'm using Win10 too... maybe @Barnacle also using Win10....We have the same problem hahaha..

**Comment by MartinMatsumoto** [comment] 2021-09-13 01:38
> I'm using Win7, sorry. People tested it on Win10, it should work with no problem.

I'm using Win10 too... maybe @Bluesky321321 also using Win10....We have the same problem hahaha..

**Comment by Q4st** [comment] 2021-09-14 14:02
I'm using Win7 x64. The program will appear to stop working！
问题签名:
  问题事件名称:	CLR20r3
  问题签名 01:	USF4ce.exe
  问题签名 02:	0.3.0.0
  问题签名 03:	5e9de2b5
  问题签名 04:	USF4ce
  问题签名 05:	0.3.0.0
  问题签名 06:	5e9de2b5
  问题签名 07:	327
  问题签名 08:	0
  问题签名 09:	System.NullReferenceException
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

Installed dx runtime library, and vc++ runtime library！I don't know how to solve it anymore. . .

I really need this tool. But I don't understand C++, and I don't know where the error is. Can you compile and test under WIN10 with vm virtual machine, or modify your code?

**Comment by MartinMatsumoto** [comment] 2021-09-14 16:27
我在Hyper-V上面安装了win7 x64位虚拟机，问题依旧。请问你是x64还是x86？

**Comment by MartinMatsumoto** [comment] 2021-09-14 16:29
I installed a win7 x64 bit virtual machine on Hyper-V, and the problem remains. Are you x64 or x86?

**Comment by MartinMatsumoto** [comment] 2021-09-14 16:30
> I'm using Win7 x64. The program will appear to stop working！
> 问题签名:
> 问题事件名称: CLR20r3
> 问题签名 01: USF4ce.exe
> 问题签名 02: 0.3.0.0
> 问题签名 03: 5e9de2b5
> 问题签名 04: USF4ce
> 问题签名 05: 0.3.0.0
> 问题签名 06: 5e9de2b5
> 问题签名 07: 327
> 问题签名 08: 0
> 问题签名 09: System.NullReferenceException
> OS 版本: 6.1.7601.2.1.0.256.1
> 区域设置 ID: 2052
> 其他信息 1: 0a9e
> 其他信息 2: 0a9e372d3b4ad19135b953a78882e789
> 其他信息 3: 0a9e
> 其他信息 4: 0a9e372d3b4ad19135b953a78882e789
> 
> Installed dx runtime library, and vc++ runtime library！I don't know how to solve it anymore. . .
> 
> I really need this tool. But I don't understand C++, and I don't know where the error is. Can you compile and test under WIN10 with vm virtual machine, or modify your code?

兄弟，我装了win7 64位虚拟机还是不行，跑不起来，点一下就没了

**Comment by Barnacle** [comment] 2021-09-14 17:05
Are you both from Asia? It looks like there is some issue with encoding or something like that.
Someone already appeared with a similar problem here: https://github.com/Barnacle/USF4-Character-Extractor/issues/4#

But I don't know what "just symbolic error" exactly means. And this person didn't respond back how it was fixed.
I will try to run this app on Japanese or Chinese version of Windows, but I can't say "when" for sure.

**Comment by MartinMatsumoto** [comment] 2021-09-15 12:13
> Are you both from Asia? It looks like there is some issue with encoding or something like that.
> Someone already appeared with a similar problem here: #4
> 
> But I don't know what "just symbolic error" exactly means. And this person didn't respond back how it was fixed.
> I will try to run this app on Japanese or Chinese version of Windows, but I can't say "when" for sure.

Yes, I am from China, we have the same problem, maybe I should learn C++...

**Comment by Barnacle** [comment] 2021-09-15 19:49
OK, this issue should be fixed now in https://github.com/Barnacle/USF4-Character-Extractor/commit/8be91a2d0bdc59ae584f23a6bfa3e1138f31c96b

It had nothing to do with encoding nor with Win10. The problem was in enabled Multisample anti-aliasing setting, so D3DDevice failed to init on some machines/GPUs.

Please check this new version: https://github.com/Barnacle/USF4-Character-Extractor/releases/tag/0.3c
If this error is gone for you, I'll close this issue.

**Comment by Q4st** [comment] 2021-09-16 01:57
Thank you, the problem is solved1!!

**Comment by MartinMatsumoto** [comment] 2021-09-16 02:01
> OK, this issue should be fixed now in [8be91a2](https://github.com/Barnacle/USF4-Character-Extractor/commit/8be91a2d0bdc59ae584f23a6bfa3e1138f31c96b)
> 
> It had nothing to do with encoding nor with Win10. The problem was in enabled Multisample anti-aliasing setting, so D3DDevice failed to init on some machines/GPUs.
> 
> Please check this new version: https://github.com/Barnacle/USF4-Character-Extractor/releases/tag/0.3c
> If this error is gone for you, I'll close this issue.

Thank you very much, this problem resolved, and I don’t have to learn C++ anymore haha

**Closed as completed** 2021-09-16 07:14 UTC
